# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-09 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=250)),
                ('newest_tweet_id', models.BigIntegerField(default=None, null=True)),
                ('oldest_tweet_id', models.BigIntegerField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='twitterstatus',
            name='twitter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.TwitterUser'),
        ),
    ]
